### ISSUE TITLE
Backend compile error

### ISSUE THREAD

**Issue by Blueforcer** [awtrix/awtrix-hd#11]
When "backend"=true im getting following message:

```
vite v2.2.1 building for production...
✓ 3 modules transformed.
.awtrix/apps/example/0.1.0/style.css        0.71kb / brotli: 0.26kb
.awtrix/apps/example/0.1.0/example.umd.js   3.13kb / brotli: 1.09kb
events.js:292
      throw er; // Unhandled 'error' event
      ^

Error: spawn C:\Users\Stephan\AppData\Roaming\npm\node_modules\@awtrix\app\node_modules\esbuild\bin\esbuild ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:269:19)
    at onErrorNT (internal/child_process.js:465:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
    at onErrorNT (internal/child_process.js:465:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'spawn C:\\Users\\Stephan\\AppData\\Roaming\\npm\\node_modules\\@awtrix\\app\\node_modules\\esbuild\\bin\\esbuild',
  path: 'C:\\Users\\Stephan\\AppData\\Roaming\\npm\\node_modules\\@awtrix\\app\\node_modules\\esbuild\\bin\\esbuild',
  spawnargs: [ '--service=0.11.13', '--ping' ]
}
```

**Comment by padarom** [comment]
Definitely a Windows issue. Doesn't show up on Linux or macOS. Everything I could find so far says that the esbuild install failed. When I manually run the executable linked above (see the "path" in your output) it works though and gives me the output I'd expect from running `esbuild` without arguments.

Not sure yet.

**Comment by padarom** [comment]
Fix verified on Windows and macOS, see commit mentioned above. Seems to be working fine. @Blueforcer Please also verify that it is working now.

**Comment by Blueforcer** [comment]
Its working on windows now!
